### ISSUE TITLE
Can't be used to replace Android's logger

### ISSUE THREAD

**Issue by echo-siddhi** [daksh7011/supercharger#1]
Since library generates tags automatically, It just accepts one argument: Message. 

While to replace Android's logger with this library would be a mess since one have to remove tag parameters and import your package.

This behavior can be improved with blank tag parameter in library to help old projects adapt/move to this library with just one easy change in their imports.

**Comment by echo-siddhi** [comment]
@daksh7011 please see PR #2

**Comment by daksh7011** [comment]
resolved this in v-0.2
